"""add lighting spec_code and loop_id columns to boq_items

Revision ID: 02ee603e4d03
Revises: ee9f02b769f0
Create Date: 2026-09-02 08:39:12.614249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ee603e4d03'
down_revision: Union[str, Sequence[str], None] = 'ee9f02b769f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_items', sa.Column('spec_code', sa.String(length=32), nullable=True))
    op.add_column('boq_items', sa.Column('loop_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_boq_items_loop_id'), 'boq_items', ['loop_id'], unique=False)
    op.create_index(op.f('ix_boq_items_spec_code'), 'boq_items', ['spec_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boq_items_spec_code'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_loop_id'), table_name='boq_items')
    op.drop_column('boq_items', 'loop_id')
    op.drop_column('boq_items', 'spec_code')
    # ### end Alembic commands ###
