"""add labor_rates table

Revision ID: 096bf7fce165
Revises: 2ba5156bafc3
Create Date: 2026-08-26 02:25:28.365424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096bf7fce165'
down_revision: Union[str, Sequence[str], None] = '2ba5156bafc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('productivity_rate', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labor_rates')),
    sa.UniqueConstraint('name', name=op.f('uq_labor_rates_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labor_rates')
    # ### end Alembic commands ###
