"""initial schema

Revision ID: 3ce37f7feb3c
Revises: 
Create Date: 2026-08-19 05:11:24.023608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce37f7feb3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('formula_or_bom', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assemblies')),
    sa.UniqueConstraint('name', name=op.f('uq_assemblies_name'))
    )
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('consultant', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('assembly_materials',
    sa.Column('assembly_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], name=op.f('fk_assembly_materials_assembly_id_assemblies')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_assembly_materials_material_id_materials')),
    sa.PrimaryKeyConstraint('assembly_id', 'material_id', name=op.f('pk_assembly_materials'))
    )
    op.create_table('drawings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('sheet_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_drawings_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawings'))
    )
    op.create_table('estimates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('total_material_cost', sa.Float(), nullable=False),
    sa.Column('total_labor_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_estimates_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimates'))
    )
    op.create_table('prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_prices_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    op.create_table('drawing_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drawing_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('source_path_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], name=op.f('fk_drawing_revisions_drawing_id_drawings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_revisions'))
    )
    op.create_table('sheets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drawing_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], name=op.f('fk_sheets_drawing_id_drawings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheets'))
    )
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('source_layer', sa.String(length=100), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('confidence_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_components_sheet_id_sheets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components'))
    )
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('route_type', sa.String(length=100), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('confidence_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_routes_sheet_id_sheets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_table('spaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('confidence_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_spaces_sheet_id_sheets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces'))
    )
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('source_sheet', sa.String(length=200), nullable=False),
    sa.Column('source_region', sa.String(length=500), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('confidence_status', sa.String(length=20), nullable=False),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_measurements_component_id_components')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_measurements_route_id_routes')),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_measurements_space_id_spaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements'))
    )
    op.create_table('boq_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('measurement_id', sa.Uuid(), nullable=False),
    sa.Column('estimate_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('fk_boq_items_estimate_id_estimates')),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], name=op.f('fk_boq_items_measurement_id_measurements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boq_items')
    op.drop_table('measurements')
    op.drop_table('spaces')
    op.drop_table('routes')
    op.drop_table('components')
    op.drop_table('sheets')
    op.drop_table('drawing_revisions')
    op.drop_table('prices')
    op.drop_table('estimates')
    op.drop_table('drawings')
    op.drop_table('assembly_materials')
    op.drop_table('projects')
    op.drop_table('materials')
    op.drop_table('assemblies')
    # ### end Alembic commands ###
