"""add_on_delete_set_null_to_layer_id_fks

Revision ID: ee9f02b769f0
Revises: 096bf7fce165
Create Date: 2026-08-31 04:44:17.066832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9f02b769f0'
down_revision: Union[str, Sequence[str], None] = '096bf7fce165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_components_layer_id_layers'), 'components', type_='foreignkey')
    op.create_foreign_key(op.f('fk_components_layer_id_layers'), 'components', 'layers', ['layer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_routes_layer_id_layers'), 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_routes_layer_id_layers'), 'routes', 'layers', ['layer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_spaces_layer_id_layers'), 'spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_spaces_layer_id_layers'), 'spaces', 'layers', ['layer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_spaces_layer_id_layers'), 'spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_spaces_layer_id_layers'), 'spaces', 'layers', ['layer_id'], ['id'])
    op.drop_constraint(op.f('fk_routes_layer_id_layers'), 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_routes_layer_id_layers'), 'routes', 'layers', ['layer_id'], ['id'])
    op.drop_constraint(op.f('fk_components_layer_id_layers'), 'components', type_='foreignkey')
    op.create_foreign_key(op.f('fk_components_layer_id_layers'), 'components', 'layers', ['layer_id'], ['id'])
    # ### end Alembic commands ###
